# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:boot-2.7.1

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      BOOT_JVM_OPTIONS: -Xmx3g -client -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Xverify:none

    steps:
      - checkout
      - boot -h

      # # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "project.clj" }}
      #     # fallback to using the latest cache if no exact match is found
      #     - v1-dependencies-
      #
      # - run: lein deps
      #
      # - save_cache:
      #     paths:
      #       - ~/.m2
      #     key: v1-dependencies-{{ checksum "project.clj" }}
      #
      # # run tests!
      # - run: lein test
